'use client';

import { useCallback } from 'react';
import { useLang } from '@/components/i18n/lang';

const arabic: Record<string, string> = {
  "Manage Lessons": "إدارة الدروس",
  "Edit Lesson": "تعديل الدرس",
  "Add New Lesson": "إضافة درس جديد",
  "Course Lessons": "دروس الدورة",
  "Add and edit the lessons for this course.": "أضف دروس هذه الدورة وعدّلها.",
  "No lessons have been added to this course yet.": "لم تُضف دروس إلى هذه الدورة بعد.",
  "Course Title": "عنوان الدورة",
  "Course Code": "رمز الدورة",
  "Course image URL (optional)": "رابط صورة الدورة (اختياري)",
  "Course Description": "وصف الدورة",
  "Category": "الفئة",
  "Price": "السعر",
  "Visibility": "الظهور",
  "Select visibility": "اختر حالة الظهور",
  "Draft (hidden)": "مسودة (مخفية)",
  "Published (public)": "منشورة (عامة)",
  "Draft courses won’t appear on public course lists.": "لن تظهر المسودات في قوائم الدورات العامة.",
  "Course is full (use waiting list)": "الدورة مكتملة العدد (استخدام قائمة الانتظار)",
  "If enabled, students will see \"Join Waiting List\" instead of \"Enroll Now\".": "عند التفعيل، سيظهر للطلاب خيار الانضمام إلى قائمة الانتظار بدلًا من التسجيل المباشر.",
  "Total Hours (for certificate)": "إجمالي الساعات (للشهادة)",
  "Instructors": "المدرّسون",
  "Primary Instructor": "المدرّس الأساسي",
  "Additional Instructors": "مدرّسون إضافيون",
  "Select primary instructor": "اختر المدرّس الأساسي",
  "Live session": "الجلسة المباشرة",
  "Live platform": "منصة البث المباشر",
  "Select live platform": "اختر منصة البث",
  "None": "بدون",
  "Jitsi room name": "اسم غرفة Jitsi",
  "Google Meet URL": "رابط Google Meet",
  "Duration": "المدة",
  "Level": "المستوى",
  "Select a level": "اختر المستوى",
  "Beginner": "مبتدئ",
  "Intermediate": "متوسط",
  "Advanced": "متقدم",
  "Saving Changes...": "جارٍ حفظ التغييرات…",
  "Creating Course...": "جارٍ إنشاء الدورة…",
  "Save Changes": "حفظ التغييرات",
  "Create Course": "إنشاء الدورة",
  "Lesson Title": "عنوان الدرس",
  "Lesson Content": "محتوى الدرس",
  "Code Embed URL (Optional)": "رابط تضمين الشفرة (اختياري)",
  "External Learning Tools": "أدوات التعلّم الخارجية",
  "Whiteboard Platform": "منصة السبورة",
  "Whiteboard URL": "رابط السبورة",
  "Coding Platform": "منصة البرمجة",
  "Coding URL": "رابط البرمجة",
  "Cloud Lab Platform": "منصة المختبر السحابي",
  "Cloud Lab URL": "رابط المختبر السحابي",
  "Whiteboard PDF": "ملف السبورة PDF",
  "Use shared whiteboard PDF (reusable across all lessons)": "استخدام ملف سبورة مشترك لجميع الدروس",
  "One global file is reused everywhere. No per-lesson uploads.": "يُستخدم ملف مشترك لجميع الدروس دون الحاجة إلى رفع ملف لكل درس.",
  "Shared template (global)": "القالب المشترك",
  "Uploading...": "جارٍ الرفع…",
  "Upload / Replace Whiteboard Template": "رفع أو استبدال قالب السبورة",
  "Copying...": "جارٍ النسخ…",
  "Use This Lesson PDF as Template": "استخدام ملف هذا الدرس كقالب",
  "Upload once, then just check the box above on any lesson to activate it.": "ارفع الملف مرة واحدة، ثم فعّل الخيار أعلاه في الدروس المطلوبة.",
  "Adding Lesson...": "جارٍ إضافة الدرس…",
  "Add Lesson": "إضافة درس",
  "e.g., Introduction to Cloud Computing": "مثال: مقدمة في الحوسبة السحابية",
  "e.g., AWSFND, PY101, AI-BASICS": "مثال: AWSFND، PY101، AI-BASICS",
  "e.g., /images/course-aws.png": "مثال: /images/course-aws.png",
  "A brief summary of what the course covers.": "ملخص موجز لمحتوى الدورة.",
  "e.g., AI, Cloud, Web Dev": "مثال: الذكاء الاصطناعي، السحابة، تطوير الويب",
  "e.g., $299 or Free": "مثال: $299 أو Free",
  "e.g., 15": "مثال: 15",
  "e.g., 8 weeks": "مثال: 8 أسابيع",
  "e.g., Introduction to Firestore": "مثال: مقدمة في Firestore",
  "The main text content for the lesson.": "المحتوى النصي الأساسي للدرس.",
  "Title must be at least 3 characters long": "يجب أن يتكون العنوان من 3 أحرف على الأقل",
  "Course code must be at least 2 characters": "يجب أن يتكون رمز الدورة من حرفين على الأقل",
  "Course code must be 12 characters or less": "يجب ألا يتجاوز رمز الدورة 12 حرفًا",
  "Use only letters, numbers, and hyphens": "استخدم الأحرف اللاتينية والأرقام والشرطات فقط",
  "Use a full URL or a /images/... path": "استخدم رابطًا كاملًا أو مسارًا يبدأ بـ /images/",
  "Description is too short": "الوصف قصير جدًا",
  "Category is required": "الفئة مطلوبة",
  "Price is required": "السعر مطلوب",
  "Duration is required": "المدة مطلوبة",
  "Title is too short": "العنوان قصير جدًا",
  "Content is too short": "المحتوى قصير جدًا",
  "Enter a valid URL": "أدخل رابطًا صحيحًا",
  "Enter a positive number": "أدخل عددًا موجبًا",
  "Enter a whole number": "أدخل عددًا صحيحًا",
  "Live URL required": "رابط الجلسة مطلوب",
  "Please provide the Google Meet URL.": "أدخل رابط Google Meet.",
  "Course Updated!": "تم تحديث الدورة",
  "Course Created!": "تم إنشاء الدورة",
  "Operation Failed": "تعذرت العملية",
  "An unexpected error occurred.": "حدث خطأ غير متوقع.",
  "Lesson Updated!": "تم تحديث الدرس",
  "Lesson Added!": "تمت إضافة الدرس",
  "Whiteboard PDF enabled for this lesson.": "تم تفعيل ملف السبورة لهذا الدرس.",
  "Whiteboard PDF disabled for this lesson.": "تم تعطيل ملف السبورة لهذا الدرس.",
  "Update Failed": "تعذر التحديث",
  "Shared whiteboard template uploaded.": "تم رفع قالب السبورة المشترك.",
  "Template Upload Failed": "تعذر رفع القالب",
  "Shared whiteboard template updated from this lesson.": "تم تحديث القالب المشترك من هذا الدرس.",
  "Copy Failed": "تعذر النسخ"
};

export function useEditorCopy() {
  const { lang } = useLang();
  const t = useCallback((text: string) => lang === 'ar' ? arabic[text] ?? text : text, [lang]);
  return { t, lang };
}
